### ISSUE TITLE
`src` getter on `img` not working

### ISSUE THREAD

**Issue by cramforce** [WebReflection/linkedom#10]
`img.src` should yield `img.getAttribute('src')`.

```js
const { parseHTML } = require("linkedom");

const { document } = parseHTML(`<img src="test.gif">`);

const img = document.querySelector("img");

console.assert(
  (document.toString() == img.src) == img.getAttribute("src"),
  `Should have src ${img.src}`
);
```

**Comment by WebReflection** [comment]
specialized classes are not there yet ... these are all within the `html` folder, but `getAttribute` and `set` works there

**Comment by cramforce** [comment]
Yep, I worked around it for the production code. I would need this to port my tests (which I'm glad I had for this project 😛)

**Comment by WebReflection** [comment]
you should always have tests anyway :stuck_out_tongue:, but all I am saying is that all specialized classes don't have all possible accessors. It's in the TODO file though, but it'll be incremental.

Feel free to file a cumulative issue in case you need more (or please tell me which accessors you use and for what element, so I can start adding these).

Maybe this issue is a good one to show how to eventually help contributing, so, for the time being, I will add onl `src` in the `HTMLImageELement` class.

**Comment by cramforce** [comment]
Sounds good. Contributing based on a sample sounds good. I need `width`, `height`, `srcset` and `href` on `link` and `a`.

**Comment by WebReflection** [comment]
`src` is in, and [these are the related changes](https://github.com/WebReflection/linkedom/commit/b7c7a47ced93179fce82aa77d89fc8124a4a750b#diff-1ea46c40e31adeeab54a066c91fbf9209606801636a6667d9af4e695c06c0044)

I will now add others by copy/pasting `src` accessor, and test the same. Will put `href` later for other classes.

**Comment by WebReflection** [comment]
@cramforce FYI `href` [is in too](https://github.com/WebReflection/linkedom/commit/6655c9126405367489d3f3f7ff494881bc521388)
