### ISSUE TITLE
observedAttributes on custom elements does not work

### ISSUE THREAD

**Issue by pYr0x** [WebReflection/linkedom#149]
the `attributeChangedCallback` and the start of observation is only fired if there is an attribute on the custom element. https://github.com/WebReflection/linkedom/blob/main/cjs/interface/element.js#L266

if you have a custom element with no attributes the [attributeChangedCallback](https://github.com/WebReflection/linkedom/blob/main/cjs/interface/custom-element-registry.js#L15) is never called.

mdm docs:
_Note that to get the attributeChangedCallback() callback to fire when an attribute changes, you have to observe the attributes. This is done by specifying a static get observedAttributes() method inside custom element class - this should return an array containing the names of the attributes you want to observe:_

we need some like `jsdom` did: https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/custom-elements/CustomElementRegistry-impl.js#L156-L162

**Comment by WebReflection** [comment]
beside the fact I don't care what jsdom does as it's not a goal of this project to be another jsdom, as stated in the README, can you please provide a minimal example of what's the issue here? the code coverage tests Custom Elements and if an element has no attributes then the callback doesn't fire even with native custom elements so I am not sure what are you after.

**Comment by pYr0x** [comment]
unhöflich antwort...
i fork this and go ahead with myself
