### ISSUE TITLE
How to use linkedom in jest, as an alternative to jsdom?

### ISSUE THREAD

**Issue by haikyuu** [WebReflection/linkedom#15]
I have a medium sized app built in React and my test suite is painfully slow. I'm using jest with react testing library. Jest relies on [jsdom](https://www.npmjs.com/package/jest-environment-jsdom) by default.

I stumbled upon this library and I'd like to see how we can use it in our project.

Is it something possible? If so, how can we do a proof of concept?

Here is the [jsdom environment file for jest](https://github.com/facebook/jest/blob/master/packages/jest-environment-jsdom/src/index.ts)

**Comment by WebReflection** [comment]
I don't know what's `VirtualConsole` in `JSDOM` and I don't think I will implement it in here (or at least it's not even in the TODO list) ... however, the README [explains how to simulate JSDOM](https://github.com/WebReflection/linkedom#simulating-json-bootstrap) and, if you'd like to try it out, basically you have to:

```js
import {VirtualConsole} from 'jsdom';
import {parseHTML} from 'linkedom';

// and then ...
lass JSDOMEnvironment implements JestEnvironment {
  dom: function JSDOM(html) { return parseHTML(html).defaultView; } | null
// ...
```

bear in mind if jest heavily relies in `JSDOM` it might be more complicated than that, but at least this is a start.

Regarding "*real-world*" projects:

  * https://twitter.com/cramforce/status/1356263121036345345
  * https://twitter.com/dgrammatiko/status/1356202691115036673
 
and so on ... which is why I've made this issue title a bit more precise.

**Comment by haikyuu** [comment]
I found a way to do something similar. But I get the following error when trying to 
```js
node.firstChild.nodeValue = text;
```

```Cannot set property nodeValue of #<NodeText> which has only a getter```
After some investigation, this is a strict mode error. But when I disable strict mode, `nodeValue` doesn't change.

I will share a reproduction repo soon.

**Comment by haikyuu** [comment]
here is a reproduction repo https://github.com/haikyuu/linkedom-test

You can reproduce the error by running `npm run test`

**Comment by WebReflection** [comment]
what's `nodeValue` for? text node or something else?

**Comment by WebReflection** [comment]
@haikyuu please try the latest `v0.4.1` which exposes `nodeValue` as setter too. I hope that fixes it 👋

**Comment by haikyuu** [comment]
Thanks @WebReflection 
They do pass. And they're blazing fast
