### ISSUE TITLE
No data returned for valid query selectors

### ISSUE THREAD

**Issue by microworlds** [WebReflection/linkedom#175]
Hi @WebReflection,

Great tool 👍 

OS: `Mac M1`
linkedom version: `^0.14.17`

When I try to target certain elements on a page, I get `NodeList(0) []`, whereas the same selection works just fine on a browser,  (Chrome, Firefox, Brave, etc.), using JSDOM and cheerio.

Target page: [https://www.google.com/search?q=latest+news](https://www.google.com/search?q=latest+news)

Selection code: `document.querySelectorAll('g-section-with-header a [style="height:92px;width:92px"] [data-atf][id*="dimg"]')`

Can you please look into this?

**Comment by WebReflection** [comment]
the selector engine is not meant to be 1:1 browsers selectors also because it doesn't understand pseudo selectors but I believe the issue here is the `[style="height:92px;width:92px"]` part ... drop that and see results, and f that's the case, please file a PR that takes that into account when/if needed.

P.S. **this module is not a crawler** but that's recently the most issues I have ... I don't care making this module a browser or a crawler, it's out of this module scope so it will be always better to use a real browser to crawl real webpages.

**Comment by WebReflection** [comment]
Keeping it open in case you'll land that PR

**Comment by microworlds** [comment]
After playing around with it a bit, I've found a way to target the needed elements with the current module. 😛 This works now:

`document.querySelectorAll('g-section-with-header a [style="height:92px;width:92px"] img[id][src*="data:image"]')`

So, my wild guess here is that the last portion of the old selector is not correct - i.e, the `[data-atf]` attribute doesn’t exist in the loaded DOM hence, the 0 results.

Issue resolved! ✅ Thanks!

**Comment by WebReflection** [comment]
maybe with a browser that data attribute is added by some script ... here no script runs whatsoever from a page but happy you worked it out 👍
