### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by zdm** [WebReflection/linkedom#212]
Hi,
Could you pleas follow standard semantic versioning - major.minor.patch?
I am always wondering, why some developers afraid to use first digit.
This adds misunderstood  to wast was changed in new release and does it contains breaking changes.

**Comment by WebReflection** [comment]
it does, because the whole Shadow DOM is now different ... nodes are not moved within the shadowRoot anymore, so that's breaking to me, even if before it wasn't really standard.

**Comment by zdm** [comment]
You replied to incorrect place

**Comment by WebReflection** [comment]
I've answered why last was a minor change (behind a `0.x.x` semver) ... it was a breaking one, so I've used the most meaningful digit. The answer is: I am following as close as I can semver, no action to take except me needing to do a better job with the change log ... time ain't helping though.

**Comment by WebReflection** [comment]
To expand though: I expect people having their own tests in place and never update out of the box this module until it reaches `1.x.x` ... however, for most things this module is kinda "*done*" but the Shadow DOM story needs special care because DSD is now almost fully available and official so expect changes in parsing and behavior. New standards added (elements internals or others) might still land as patch before `1.x.x` but breaking changes on the structure around Shadow DOM will be flagged as minor until it's reasonably done.

**Comment by zdm** [comment]
Yes, I understand, thank you.
I mean that it is always better to follow standards, so we can manage required versions clearly using `^x.x.x` and `~x.x.x`.
Why not release `25.0.0` instead of `0.25.0`, this will be clear for everybody without additional questions?
And with your approach it is impossible to make patch release, this is not a big problem, but creates additional limitations.

**Comment by zdm** [comment]
By convention versions below `1.0.0` are considered as pre-releas.
First public releas is `1.0.0` and so on.

**Comment by WebReflection** [comment]
I am planning to have `1.0` once DSD is done among other issues still open ... after that I doubt there will be breaking changes so hopefully things will be better then. I have modules downloaded 100M+ monthly with full semver in place, it's not that I am afraid to use the first digit, is rather that I don't think this module is ready for its first `1.` release.

**Comment by zdm** [comment]
ok, thank you.
