### ISSUE TITLE
What are some possible uses cases?

### ISSUE THREAD

**Issue by mrjjwright** [WebReflection/linkedom#28]
This seems like an efficient way to represent the DOM.    What is an example real life use case that you thinks represents the sweet spot usage for this lib?

**Comment by haikyuu** [comment]
I've started using it for testing as a replacement for JSDOM. its speed is amazin in comparison but JSDOM's scope is huge so there are some cases where Linkedom won't work because it's missing some JSDOM properties. Nevertheless the speed difference is worth it as you can alway's drop back to JSDOM if needed.

Some people use it for SSR too.

**Comment by WebReflection** [comment]
thanks @haikyuu, curious to know what's missing, beside agreeing *JSDOM* scope is huge, and it's not this library purpose to implement everything *JSDOM* has. A list of *great to have* missing features would help me out eventually prioritizing, so if you ever get a chance to write down one as issue, I'd very much appreciated that 👋

**Comment by haikyuu** [comment]
Sure. I'll do that as I am trying to write my new tests using LinkeDOM.
