### ISSUE TITLE
Why esm + cjs in a source code?

### ISSUE THREAD

**Issue by ThePlenkov** [WebReflection/linkedom#290]
Hi! 

I am trying to understand then purpose of having two folders cjs + esm in a source code.

I see you're already using rollup. Isn't it better to migrate esm to typescript may be and set up Rollup to build both cjs and esm?

I think in this case it would help you to reduce the size of the project. The reason I'm asking - I see that types are not in sync with what you actually have in the source code.

Writing a project in TS + bundling with rollup would help to publish actual cjs + esm libs but also would provide all types right from a source code.

I know it sounds like massive refactoring, but in fact it may be not that much work since the code is already there.

**Comment by WebReflection** [comment]
> I know it sounds like massive refactoring

not only that, and I have zero time and personally zero interest in making this project TS, if some type is out of sync it's way easier to contribute fixing JSDoc TS.

The CJS folder is an automation, it costs nothing to maintain, it's part of the build process.

Many are still on CJS on the server so that's not going to change.

Many others trust current pure JS implementation and because TS might produce a different outcome if I use TS only things, outcome I won't control anymore, I am skeptic that would add anything to this project.
