### ISSUE TITLE
Weird self closing table cell tags

### ISSUE THREAD

**Issue by qwelias** [WebReflection/linkedom#31]
Example from the wild web:
http://dedimania.net/tmstats/?do=stat&Envir=TMU-Island&MapOrder=DATE-DESC&Show=MAPS

It has this sort of stuff: `<td someattr="somevalue" /td>`

No idea how standard compliant this is, but Chrome parses it without any problems.

Linkedom doesn't see that it's a _"self closing"_ `td` and puts subsequent tag into it.

Feel free to close, this looks real sketchy :)

**Comment by WebReflection** [comment]
this is out of *LinkeDOM* scope, as that's an issue to eventually file to [htmlparser2](https://github.com/fb55/htmlparser2), but here the parser is *XML* friendly, because of libraries using `<element />` in the wild, and I'd like to support that in here, as nobody ever mentioned to put a slash without closing the tag.

however, if there is an option in *htmlparser2* to deal with these kind of silly layouts, I'd consider using it.

**Comment by WebReflection** [comment]
On a second thought, these sketchy cases are a regexp away from being solved, as in `/ \/(\w+)>/g, "></$1>"` replace away, and slowing down 99% of cases instead of promoting good HTML practices is *not* really what this module is after. So this is a won’t fix until the right bug is filed to the right module, and the perf lost is *not* relevant.
