### ISSUE TITLE
parseHTML(htmlStr).defaultView -- returns undefined

### ISSUE THREAD

**Issue by Nashorn** [WebReflection/linkedom#34]
Strange. I am currently trying to swap out the JSDOM api I am using for Linkedom. But i am always getting undefined for default view. I even tried running it from console:
```parseHTML("<html><body>Hello</body></html>").defaultView```

and its still undefined. I don't know if JSDOM is conflicting with it, because it's still being imported in another area of the system.

Is that possible? BTW - I am able to test is from the console because I require it from my Electron app and assign it to the window, so i get access:

In Electron:
```
var {parseHTML} = require('linkedom');
window.parseHTML=parseHTML;
```

**Comment by WebReflection** [comment]
Updated the README, it was based on `new DOMParser().parseFromString(html).defaultView`, but `praseHTML` already returns a `window` like object.

https://github.com/WebReflection/linkedom#simulating-json-bootstrap

👋

P.S. this module does **not** pollute the global context/scope with anything so it cannot conflict with anything else.

**Comment by Nashorn** [comment]
It works!
Here's how i had to import from nodejs/electron though:

```
var {parseHTML} = require('linkedom');
function JSDOM(html) { 
    return parseHTML(html);
}
```

And:
```var doc = new JSDOM(src_text).document;```

Now to replace everywhere I am using JSDOM. Works beautiful. This may very well be the next leader over jsdom. I hope the project continues.

**Comment by WebReflection** [comment]
> I hope the project continues.

the project idea was to demonstrate a different approach to classic `class Element { constructor() { this.attributes = []; this.childNodes = []; } }` approach, and so far it's keeping its promises.

the *jsdon* (not *JSDOM*) idea came out of it, but it's also offering a `jsdon/parse` minimal, simplified, approach, that is showing interesting results: lighter heap, faster results *unless* there is *DOM* manipulation.

That being said, all the mechanism to work "*for real*" out there are in, and all my projects are switching to this module, instead of *basicHTML*, so that guarantee this project is more than active, but if nothing ever similarly complex will show up better performance, all you'll have to do is change the module name, as this module provides a *Web standard* `DOMParser` class, which is the entry point for everything, so that *everything* is possible once this work for everyone.

I'm not sure I've added more confusion than I meant to solve, but the *TL;DR* is: **yes, linkedom will stay around for long time**, as there's so much code in here, including tests, that only a *fool* would abandon for no reason 😉
