### ISSUE TITLE
HTML Entities cannot be outputted

### ISSUE THREAD

**Issue by henricook** [WebReflection/linkedom#62]
For a large variety of use cases it is desirable to have HTML entities in Linkedom output. Currently outputting an element as a string decodes these entities, so for example an `&amp;` appears as an `&` and an `&nbsp;` appears as a ` ` (space).

Here's a simple to test to demonstrate desired behaviour:

```
const {document} = parseHTML('<!DOCTYPE html><html id="html" class="live"><!--&lt;hello&gt;-->&lt;hello&gt;</html>');

document.documentElement.innerHTML = '<div>Foo&nbsp;&nbsp;&nbsp;Bar</div>'

// Assertion fails currently (desired behaviour)
assert(document.documentElement.toString(), '<div>Foo&nbsp;&nbsp;&nbsp;Bar</div>')

// Assertion passes currently
assert(document.documentElement.toString(), '<div>Foo    Bar</div>')
```

**Comment by WebReflection** [comment]
OK ... this will be a huge change ... please be patient on this one, as it affects a lot of code.

**Comment by WebReflection** [comment]
@henricook I'd be very happy if you could look at the MR. The test/use case has been slightly improved and added too. This will be published as major if you're happy with the resulting behavior, it looks OK to me, but maybe there's something I'm missing.

Thanks.

**Comment by henricook** [comment]
Thanks @WebReflection ! Tests look good at a glance, I'll give it a try on my real codebase this week

**Comment by WebReflection** [comment]
Actually… my implementation is way too naive. I think I should leave everything as is and unescape only on data … I need to verify more few scenarios with the real DOM

**Comment by WebReflection** [comment]
OK, this opened somehow a Pandora's box. There are tons of things to consider, and a slowdown, on top of a new dependency that is not super lightweight anymore.

Bottom line: do you know any other char that should *not* be modified when present in the layout? it looks like not a single library cares enough about this `&nbsp;` case, so that all decoders end up transforming it as space, even if I understand that's not desired.

I had to re-iterate 4 times over the PR because fixed one thing, broke another ... now it's a funny dance, but it looks like it's the expected/right one, and no edge cases should escape.

I am not super happy about the third party slow dependency, but as 100M downloads would suggest this is reliable, I'm OK in having it in there too, yet I had to fix cloning and other few parts, and now LinkeDOM is 1.1x slower than before, due all this parsing around expectations for text nodes.

Anyway, please let me know if this works for you, otherwise I'll re-think, re-simplify, again, the whole dance.

**Comment by WebReflection** [comment]
P.S. I am *really* considering to bring `html-escaper` back and use that, without normalizing the rest of the text like the DOM does.

Thing is, stuff like `&copy;` or any other entity now gets parsed, to reflect `innerHTML`, but this makes the produced outcome less portable across platforms (utf-8 VS PHP default shenanigans, to name one).

**Comment by henricook** [comment]
Interesting stuff. I think my project only cares about `&amp;` and `&nbsp;` - if that's of any help. Sorry to hear re: slow dependency, we also love Linkedom's speed!

**Comment by WebReflection** [comment]
I think `&amp;` has never been an issue, but I also think `&nbsp;` is the only weirdo here ... plot twist, LinkeDOM, as it was before, was just fine, except it didn't re-output `&nbsp;` as entity, but as `String.fromCharCode(160)`.

I don't know why that's an issue for you in the first place thought, but if that's really important to change, I'd be happy to completely drop all MRs around and just use a RegExp in Text and Comments to produce that, once stringified.

It looks it's really the only thing missing, and your MR was just misplaced, imho, but maybe better than current one with extra dependencies and slower outcome.

**Comment by WebReflection** [comment]
@henricook OK, I think current version is fine. If you find anything odd, please let me know. This version won't need a major bump, as it's just the `&nbsp;` that goes back, but other chars are decoded as it was before, so it's not really a breaking change (or better, it shouldn't ... in general).

**Comment by WebReflection** [comment]
@henricook how about I just merge https://github.com/WebReflection/linkedom/pull/68 as patch and you tell me if that works for you?

**Comment by henricook** [comment]
Sure, if you wish! :-)

**Comment by WebReflection** [comment]
@henricook done

**Comment by henricook** [comment]
I'm sorry this took me so long, it appears this works for us up to version 0.9.3 and then something breaks again. This is fine for us right now but we will eventually try to upgrade, i'll be in touch and thanks again!
