### ISSUE TITLE
new Text throws illegal constructor error

### ISSUE THREAD

**Issue by matthewp** [WebReflection/linkedom#90]
The following throws:

```js
const window = parseHTML(`
  <html lang="en">
  <head><title>Site</title></head>
  <body></body>
  </html>
`);

new window.Text();
```

Testing in Firefox and Chrome these do not throw, but return an empty text node.

I believe the reason is that the window proxy created in `defaultView` is preferring the facade Text over the imported Text: https://github.com/WebReflection/linkedom/blob/53138c21939f7d55f2d593462321fcfabcd81aa0/esm/interface/document.js#L132

Happy to submit a PR for this. Would the fix be to add Text to the switch statement and use imported Text instead?

**Comment by WebReflection** [comment]
All constructors need to know the document they're working with. If `Text` is needed (why not `document.createTextNode`?) then the window (defaultView) should return `Text.bind(null, this)` or follow the `Image` dance for text too.

**Comment by matthewp** [comment]
Binding makes sense. I'm trying to get Atomico working with linkedom, which does this strange thing and extends Text (see here: https://github.com/atomicojs/atomico/blob/32da92904405366d667608e95af109bb8f52f2e8/src/render.js#L38-L43). Another thing they are doing is adding their own nodeType getter which will throw when linkedom's Node is setting the nodeType. This might be stretching the definition of "close but not too close" talked about in the linkedom readme, so this issue might be worth closing.

**Comment by WebReflection** [comment]
`nodeType` as `-1` is reserved here, it's the closing node, so I'd rather avoid everything exploding due weird artifacts needed somewhere else where `instanceof`, after extending a class, wasn't considered a better idea (but I understand the hack, because `instanceof` might be slower than `nodeType` check, in these projects - it is faster in real DOM though ...).

I am not sure I want other projects decisions pollute this code with any weird stuff they do for their own internal use cases, but if you need any help in solving that issue, with a wrapper or something, I'd be happy to help out.

**Comment by WebReflection** [comment]
P.S. a `FragmentMarker` should use a fragment nodeType, imho, and that's `11`, not `-1`

**Comment by matthewp** [comment]
Thanks, I agree that this seems like an internal thing that shouldn't pollute linkedom, so closing. Btw, I'm not involved in atomico I'm just trying to get it to work in an ssr runtime I'm working on separately (https://github.com/matthewp/ocean) that's powered by linkedom. I think fixing this in a wrapper layer is the right approach.
