### ISSUE TITLE
Duplicated CSSStyleDeclaration

### ISSUE THREAD

**Issue by Kal-Aster** [WebReflection/linkedom#92]
Since #74 linkedom depends on `cssom` which implements `CSSStyleDeclaration` class.
Because of this, the implementation of the same class located in `interface/css-style-declaration.js` is redundant, and actually brings also bug, having it a very poor implementation of the `CSS Object Model`, compared to that of `cssom`.

All the imports to `interface/css-style-declaration.js` should be redirected to `cssom`

I'd make a PR, if I haven't one opened already.

**Comment by WebReflection** [comment]
>  is redundant, and actually brings also bug, having it a very poor implementation of the CSS Object Model, compared to that of cssom.

but it's fast, right?

**Comment by Kal-Aster** [comment]
Surely, but it hasn't many function, like `setProperty`, which instead `cssom` has.
Or we implement other functionality trying to keep it as fast as it is now or we switch to `cssom`

**Comment by WebReflection** [comment]
I need to see if that class is on the critical path for rendering. If it's not, I am OK switching to a better class instead of reinvent the wheel, since the dependency is already in, but if that's the case, maybe we can think about some lazy-upgrade as dealing with CSS as if it was a browser is out of this module scope, there's JSDOM for that, here there's no goal to be 1:1 with all the Web standards.

I hope this makes sense.

**Comment by Kal-Aster** [comment]
Thank you.

Reading your last message and the fact this is another issue I'm encountering with this library make me think that probably I should flag `JSDOM` to `riot/ssr` (a library that I use that depends on `linkedom`)...

**Comment by WebReflection** [comment]
So ... reason I am using my class is that it's hooked with MutationObservers and Custom Elements observed attributes.

If I use any foreign class I need to be sure changes in there are reflected, otherwise nothing works.

Is there anything in particular that is not working, or why is the fact two modules have same `CSSStyleDeclaration` an issue?

**Comment by Kal-Aster** [comment]
The only real problem, beyond the absence of some functionality, could be an expression where a style declaration object is compared with `instanceof` with the class and it won't work because it is an instance of the class of the other library. I think that this is a rare edge-case, so we can live along with that.

I found this because I tried using `setProperty` function, which isn't implement, so the main issue is the lack of functionality.

**Comment by WebReflection** [comment]
I could bring in the class and extend it: instanceof would work, but I need to check the rest of the methods.

**Comment by WebReflection** [comment]
Turns out, rollup found that cssom `CSSStyleDeclaration` has some circular dependency, causing issues even on  build ... I don't think I should use that directly, but if that was your concern, I think there's a cssom issue to solve first.
