### ISSUE TITLE
Streaming HTML

### ISSUE THREAD

**Issue by devinellis** [WebReflection/linkedom#98]
I’m curious if it would be possible to use a stream, or loop through chunks of HTML into the parser? Looking at the source code I’m not sure if it’s possible, but the benefits for my use-case are:
- less memory usage (in theory?)
- Ability to drop nodes before adding them to the document (eg script tags)
- Stop parsing once it has met certain criteria

**Comment by devinellis** [comment]
Sorry for the vagueness! I am crawling web sites and looking to use @mozilla/readability to extract the main content of the body.

The simplest solution is to wait for the whole response string and pass it into your parser, but sometimes all I need is the `<head>`, or the first N characters (or Nodes) of the body.

I could pre-process the HTML, but it seems ideal to do it all in one pass.

I like the interface of fb55/htmlparser2, and another benefit would be I’m not storing the whole document in memory twice: once as a string, and then as linkedon arrays.

Thanks for the quick reply!

**Comment by WebReflection** [comment]
> I like the interface of fb55/htmlparser2

which is what we use in here too ... so ... just use that instead of this library? 'cause this library is for creating content, not for parsing streamed content, and I have no intention to create a dedicated parser for that, as I have honestly zero time but also this is not the project you should look after, because parsing streams means a constantly broken linked list of nodes, so it plays badly with the premisis of this lib.

Apologies if that's not the answer you were looking for, but I think you need to create what you need there, and htmlparser2 would be my hint too, as that's incremental, yet I have no idea if it works with streams, but if it does, your job is half-done.

Closing as no action will be taken, but feel free to ask more if needed.
